import type { Meta, StoryObj } from "@storybook/react";

import { MajIconButton } from "../../components";

const meta: Meta<typeof MajIconButton> = {
    title: "MajUi/MajIconButton",
    component: MajIconButton,
    argTypes: {
        shade: {
            options: ["Light", "Solid"],
            control: { type: "radio" },
        },
        variant: {
            options: [
                "360",
                "address-book",
                "angle-down",
                "angle-left",
                "angle-right",
                "angle-up",
                "arrow-down-to-line",
                "arrow-down",
                "arrow-left",
                "arrow-right",
                "arrow-right-arrow-left",
                "arrows-rotate",
                "arrow-up",
                "arrow-up-from-bracket",
                "arrow-up-to-line",
                "backward-step",
                "barcode-read",
                "bars",
                "bell",
                "bolt-lightning",
                "box-open",
                "bug",
                "calendar-days",
                "camera-viewfinder",
                "caret-down",
                "caret-left",
                "caret-right",
                "caret-up",
                "cart-flatbed-boxes",
                "cart-shopping",
                "chair-office",
                "chart-column",
                "chart-simple",
                "check",
                "circle-check",
                "circle-exclamation",
                "circle-info",
                "circle-minus",
                "circle-question",
                "circle-user",
                "circle-x-mark",
                "circle",
                "clipboard-list",
                "clock",
                "comment",
                "credit-card",
                "cross-hairs",
                "database",
                "ellipsis-vertical",
                "ellipsis",
                "envelope",
                "equals",
                "expand",
                "eye-slash",
                "eye",
                "file-arrow-down",
                "file-arrow-up",
                "file-invoice",
                "filter",
                "flash",
                "forward-step",
                "gauge",
                "gear",
                "gears",
                "globe",
                "grid-horizontal",
                "grid",
                "grip-dots",
                "headset",
                "heart-pulse",
                "house",
                "location-dot",
                "lock",
                "magnifying-glass",
                "minus",
                "paperclip",
                "pause",
                "pencil",
                "picture",
                "play",
                "plus",
                "print",
                "repeat",
                "share",
                "shuffle",
                "sort",
                "square-facebook",
                "square-instagram",
                "square-linkedin",
                "square-list",
                "square-youtube",
                "star",
                "store",
                "tag",
                "thumbs-down",
                "thumbs-up",
                "trash-can",
                "triangle-exclamation",
                "truck",
                "twitter-x",
                "unlock",
                "upload",
                "user",
                "volume-slash",
                "volume",
                "wave-pulse",
                "x-mark",
            ],
            control: { type: "select" },
        },
    },
};

export default meta;
type Story = StoryObj<typeof MajIconButton>;

export const Primary: Story = {
    args: {
        shade: "Light",
        variant: "360",
    },
};
