import { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Variants: Story;
export declare const Sizes: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
export declare const WithLeftIcon: Story;
export declare const WithRightIcon: Story;
export declare const FullWidth: Story;
